### ISSUE TITLE
Online interpreter `m` command

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [VTCAKAVSMoACE/Vitsy#1]
[This](http://vitsy.tryitonline.net/#code=MW1OCiAgTgogIE5OCiAgTk5O&input=) should output _something_, right? I assume the `m` command is broken.

**Comment by addisoncrump** [comment]
It absolutely does (m is not broken) - it outputs the following error (with Debug on):

<pre>Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:418)
    at java.util.ArrayList.get(ArrayList.java:431)
    at com.VTC.vitsy.Vitsy.opHandle(Vitsy.java:428)
    at com.VTC.vitsy.Vitsy.methodHandler(Vitsy.java:105)
    at com.VTC.vitsy.Vitsy.opHandle(Vitsy.java:245)
    at com.VTC.vitsy.Vitsy.main(Vitsy.java:88)</pre>
